version: "3.8"

services:
  harperdb:
    image: harperdb/harperdb:latest
    container_name: harperdb
    environment:
      - HDB_ADMIN_USERNAME=admin
      - HDB_ADMIN_PASSWORD=password
    ports:
      - "9925:9925"
      - "9926:9926"
    volumes:
      - harperdb-data:/var/lib/harperdb

volumes:
  harperdb-data:
